# TODO --> Aun esta en prueba 
[metadata]
name = "NestJs Api"

[[variables]]
name = "author"
prompt = "Project's author?"
type = "string"
default = "arekkazu"

[[variables]]
name = "description"
prompt = "Tiny description: "
type = "string"
default = "Building an API using NestJs"

[[variables]]
name = "description"
prompt = "Tiny description: "
type = "string"
default = "Building an API using NestJs"

