[package]
name = "axer"
version = "0.1.0"
edition = "2024"

[dependencies]
inquire = "0.9.1"
clap = "4.5.53"
colored = "3.0.0"
fs_extra = "1.3.0"
directories = "6.0.0"
# PARA TOML
serde = { version = "1.0.228", features = ["derive"] }
handlebars = "6.3.2"
toml = "0.9.8"

